dependencies {
    compileOnly project(':dongsan-core')

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.redisson:redisson-spring-boot-starter:3.48.0'
}

// application.yml 설정 파일 복사
tasks.register('copyConfig', Copy) {
    from '../../Config/storage/redis'
    include "application*.yml"
    into 'src/main/resources'
}

processResources.dependsOn('copyConfig')

